# Generated by Django 5.0.7 on 2024-07-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salaey',
            new_name='salary',
        ),
    ]
